### ISSUE TITLE
Hi, could you please provide the .pth that have been trained well ? 

### ISSUE THREAD

**Issue by kiinchen** [gitouni/CalibNet_pytorch#1]

**Comment by gitouni** [comment]
The `.pth` file is so big (140MB) and cannot be uploaded to github (limited to 25MB). Have you met any problem in training this network?

**Comment by gitouni** [comment]
You can downlaod it from my released [file](https://github.com/gitouni/CalibNet_pytorch/releases/download/0.0.2/cam2_oneiter_best.pth) now.

**Comment by kiinchen** [comment]
I am writing a review of related research, I hope to save time to analyze each method, thank you very much for your help.

**Comment by gitouni** [comment]
> I am writing a review of related research, I hope to save time to analyze each method, thank you very much for your help.

Given there are still unsolved problems of this implementation, it is strongly recommended to implement CalibNet with its original (official) implementation by TensorFlow.
