### ISSUE TITLE
dataset issues

### ISSUE THREAD

**Issue by Hukiwi** [gitouni/CalibNet_pytorch#12]
Thank you for sharing this repo!
I'm trying to run the train.py script, but I get the following error:

dataset.py", line 116, in <listcomp>
    self.kitti_datalist = [pykitti.odometry(basedir,seq,frames=frame) for seq,frame in zip(seqs,frame_list)]  
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/pykitti/odometry.py", line 35, in __init__
    self._load_poses()
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/pykitti/odometry.py", line 220, in _load_poses
    lines = [lines[i] for i in self.frames]
  File "/root/anaconda3/envs/yolov5/lib/python3.8/site-packages/pykitti/odometry.py", line 220, in <listcomp>
    lines = [lines[i] for i in self.frames]
IndexError: list index out of range

How can I solve it?

**Comment by gitouni** [comment]
I think the problem lies in that some datasets you designated in the config file are not downloaded in the directory. If you double check the datasets and still have problems, show your directory tree and config file here.

**Comment by Hukiwi** [comment]
The datasets designated in the config file are all downloaded in the directory. 
The contents of the directory tree and config file  are shown in the following figure：
![Uploading 屏幕截图 2024-05-09 172507.png…]()
![Uploading 屏幕截图 2024-05-09 172543.png…]()

**Comment by Hukiwi** [comment]
The datasets designated in the config file are all downloaded in the directory.
and the contents of the directory tree and config file are shown below:
CalibNet_pytorch/
  --|data/
      --|poses/
          --|00.txt
          --|01.txt
          --...
      --|sequences/
          --|00/
              --|image_2/
              --|velodyne/
              --|calib.txt
              --|times.txt
          --|01/
          --|02/
          --...
  --...


dataset:
  train: [0,1,2,3,4,5,6,7]
  val: [8,9,10]
  test: [11,12,13]
  cam_id: 2  
  voxel_size: 0.1
  pooling: 3  
  extend_ratio: [2.5,2.5]

**Comment by gitouni** [comment]
set train set to「0」and val to 「1」and Try again. Remember to Delete the cache file“data_len.json" as well.

**Comment by Hukiwi** [comment]
set train to「0」and val to 「1」, the data reading works fine, is there something wrong with the file I downloaded?

**Comment by gitouni** [comment]
> set train to「0」and val to 「1」, the data reading works fine, is there something wrong with the file I downloaded?

I think so. You can debug the python script and check the consistency between the variable "frame" and the actual number of files in your directory. Furthermore, you can set other sequence numbers for "train" and see which one causes error.

**Comment by gitouni** [comment]
Sorry, someone raised another issue to remind me that the update on `dataset.py` causes  this problem. I changed it to the old version and you can download it again and have a try.
