### ISSUE TITLE
TypeError: BaseKITTIDataset.__init__() got an unexpected keyword argument 'extend_ratio'

### ISSUE THREAD

**Issue by nofreewill42** [gitouni/CalibNet_pytorch#3]
First of all, thank you for sharing this repo!

So I'm trying to run the test.py script.
Kitti dataset is downloaded and unzipped, first the color, then velodyne and then calib with overwriting, as described in the Dataset Preparation section.
I've activated my venv envorinment, I then ran the given `python test.py ...` command and iteratively pip installed everything it said my environment is lacking.
But in the end I get the following error 
```
(venv) nofreewill@nofreesill:~/Documents/CalibNet_pytorch$ python test.py --inner_iter=1 --pretrained=./checkpoint/cam2_oneiter_best.pth --skip_frame=1 --pcd_sample=-1
args have been received, please wait for dataloader...
Traceback (most recent call last):
  File "/home/nofreewill/Documents/HomeOffice/CalibNet_pytorch/test.py", line 95, in <module>
    test_dataset = BaseKITTIDataset(args.dataset_path,args.batch_size,test_split,CONFIG['dataset']['cam_id'],
TypeError: BaseKITTIDataset.__init__() got an unexpected keyword argument 'extend_ratio'
```

**Comment by nofreewill42** [comment]
What is happening, what do I do wrong?

**Comment by gitouni** [comment]
> First of all, thank you for sharing this repo!
> 
> So I'm trying to run the test.py script. Kitti dataset is downloaded and unzipped, first the color, then velodyne and then calib with overwriting, as described in the Dataset Preparation section. I've activated my venv envorinment, I then ran the given `python test.py ...` command and iteratively pip installed everything it said my environment is lacking. But in the end I get the following error
> 
> ```
> (venv) nofreewill@nofreesill:~/Documents/CalibNet_pytorch$ python test.py --inner_iter=1 --pretrained=./checkpoint/cam2_oneiter_best.pth --skip_frame=1 --pcd_sample=-1
> args have been received, please wait for dataloader...
> Traceback (most recent call last):
>   File "/home/nofreewill/Documents/HomeOffice/CalibNet_pytorch/test.py", line 95, in <module>
>     test_dataset = BaseKITTIDataset(args.dataset_path,args.batch_size,test_split,CONFIG['dataset']['cam_id'],
> TypeError: BaseKITTIDataset.__init__() got an unexpected keyword argument 'extend_ratio'
> ```

My apologies to forget to update some files. the `extend_ratio` is an argument to enlarge the FOV of the camera, aiming to  project more possible corresponding LiDAR points while the initial calibration is bad. I updated [dataset.py](https://github.com/gitouni/CalibNet_pytorch/blob/main/dataset.py) as well as other possible changed files. It would be fixed now. (At least I hope so)

**Comment by gitouni** [comment]
You can reopen this issue if there are still issues.

**Comment by nofreewill42** [comment]
Oh yeah it's now solved, thank you very much for the quick solution! ^^
