### ISSUE TITLE
A question about INFO - 2023-10-10 21:01:41,619 - test - [03201|05263],mdx:0.0624. what is mdx?

### ISSUE THREAD

**Issue by cchester25** [gitouni/CalibNet_pytorch#9]

**Comment by gitouni** [comment]
Please refer to
https://github.com/gitouni/CalibNet_pytorch/blob/25fdfa519ea0963d80ad76a0817af886cb144442/test.py#L67-L71
It is the mean of the defined residual vector `res_npy`.

**Comment by cchester25** [comment]
> Please refer to
> 
> https://github.com/gitouni/CalibNet_pytorch/blob/25fdfa519ea0963d80ad76a0817af886cb144442/test.py#L67-L71
> 
> 
> It is the mean of the defined residual vector `res_npy`.

Thanks for the answer, I would like to ask why the sequences 11, 12 and 13 must be present at the same time when testing, can't we just test a particular sequence?

**Comment by gitouni** [comment]
> > Please refer to
> > https://github.com/gitouni/CalibNet_pytorch/blob/25fdfa519ea0963d80ad76a0817af886cb144442/test.py#L67-L71
> > 
> > It is the mean of the defined residual vector `res_npy`.
> 
> Thanks for the answer, I would like to ask why the sequences 11, 12 and 13 must be present at the same time when testing, can't we just test a particular sequence?

The sequence number can be designated in `config.yml`:
https://github.com/gitouni/CalibNet_pytorch/blob/25fdfa519ea0963d80ad76a0817af886cb144442/config.yml#L1-L4

For example, to test CalibNet on only sequence 11, you just need to change the `test` parameter to `[11]`.
